name: Build and Test
inputs:
  github_token:
    description: The Github token to authenticate gh CLI.
    required: true

runs:
  using: composite
  steps:
    - name: DEBUG
      shell: bash
      env:
        # The tests make use of Github-specific functionality (e.g. gh).
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        gh auth status

    - name: Execute Tests
      shell: bash
      env:
        # The tests make use of Github-specific functionality (e.g. gh).
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        bazelisk test //... 

    - name: Build Anything Not Tested
      shell: bash
      run: |
        bazelisk build //... 

    - name: Ensure Bazel packages covered by bzlformat_pkg
      shell: bash
      run: |
        bazelisk run //:bzlformat_missing_pkgs_test
