name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  macos_build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - uses: cgrindel/gha_set_up_bazel@v2
      with:
        repo_name: github_snippets
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
