name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  macos_build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
    - uses: cgrindel/gha_set_up_bazel@v1
      with:
        repo_name: github_snippets
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

