name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  macos_build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
    - uses: cgrindel/gha_set_up_bazel@v2
      with:
        repo_name: github_snippets
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
