name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]

jobs:
  macos_build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: cgrindel/gha_set_up_bazel@v2
      with:
        repo_name: github_snippets
    - uses: ./.github/actions/build_and_test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
